name: running-app

volumes:
  database:

services:
  database:
    build:
      target: db
    env_file: .env
    ports:
      - 8090:5432
    volumes:
      - database:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    logging:
      driver: none
    env_file: .env
    ports:
      - 5050:80
  website:
    build:
      target: website
    command: sh -c "yarn start:website"
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./packages/website
          target: /running/packages/website
          action: sync
  server:
    build:
      target: server
    command: sh -c "yarn start:server"
    ports:
      - 8080:8080
    develop:
      watch:
        - path: ./packages/server
          target: /running/packages/server
          action: sync
